export const COURT_SERVICE_PAGES = {
  'delhi-high-court-advocate': {
    slug: 'delhi-high-court-advocate',
    title: 'Delhi High Court Advocate',
    metaTitle: 'Delhi High Court Advocate | Representation & Litigation | legalgroup',
    metaDescription: 'Consult a Delhi High Court advocate for writs, civil and criminal appeals, service matters, commercial disputes and other High Court proceedings.',
    introTitle: 'Prepared representation for proceedings before the Delhi High Court',
    intro: 'Representation before the Delhi High Court calls for more than filing pleadings. It requires careful legal research, procedural understanding, evidence assessment and a strategy aligned with the client’s practical objective.',
    introSecond: 'Our court services support individuals, families, professionals and businesses with structured preparation for writ jurisdiction, civil and criminal matters, appeals, constitutional questions, service disputes and commercial litigation.',
    servicesTitle: 'Delhi High Court legal services',
    services: [
      ['Writ petitions', 'Assistance with public law remedies, administrative decisions and constitutional issues.'],
      ['Civil appeals', 'Strategic preparation for appeals, interim applications and civil disputes.'],
      ['Criminal appeals and bail', 'Representation for appellate remedies, bail and anticipatory bail matters.'],
      ['Service matters', 'Advice and representation concerning employment, disciplinary and service disputes.'],
      ['Commercial disputes', 'Court support for business, contract, arbitration and commercial litigation.'],
      ['Property and family appeals', 'Careful preparation for property, matrimonial and related appellate proceedings.'],
    ],
    courtTitle: 'Matters commonly brought before the Delhi High Court',
    courtText: 'The Delhi High Court hears matters involving constitutional and administrative law, civil and criminal appeals, commercial disputes, service law, intellectual property and other proceedings within its jurisdiction. An initial consultation helps identify the appropriate remedy, forum and procedural next step without assuming that every dispute requires the same approach.',
    clients: ['Individuals', 'Families', 'Business owners', 'Companies', 'Professionals', 'Parties to civil or criminal proceedings'],
    faqs: [
      ['How can a Delhi High Court advocate help with my case?', 'A lawyer can review the facts and documents, identify the appropriate legal remedy, explain the procedure and prepare representation suited to the issues before the Court.'],
      ['Can I consult a lawyer before filing a case?', 'Yes. Early advice can help clarify jurisdiction, limitation, available remedies, documents and the practical risks of filing or responding to proceedings.'],
      ['Can a lawyer represent me in an appeal?', 'A lawyer may advise and represent a client in an appeal or related application, subject to the facts, procedural requirements and the nature of the order being challenged.'],
      ['What documents should I bring for an initial consultation?', 'Bring the relevant orders, notices, pleadings, contracts, correspondence and a clear chronology. Original documents should be retained safely; copies or scans are usually sufficient for an initial review.'],
      ['How long can High Court proceedings take?', 'Timelines vary substantially with the type of proceeding, the record, interim issues and the Court’s schedule. No responsible lawyer can promise a fixed outcome or duration.'],
    ],
  },
  'supreme-court-lawyer-delhi': {
    slug: 'supreme-court-lawyer-delhi',
    title: 'Supreme Court Lawyer Delhi',
    metaTitle: 'Supreme Court Lawyer Delhi | Appeals & SLP Representation | legalgroup',
    metaDescription: 'Seek legal consultation for Supreme Court representation from Delhi, including Special Leave Petitions, civil and criminal appeals, review and transfer petitions.',
    introTitle: 'Careful preparation for Supreme Court proceedings',
    intro: 'Supreme Court proceedings require a focused understanding of the record, the question of law and the procedural route available. Preparation must be precise, economical and grounded in the orders and evidence already before the Court.',
    introSecond: 'Our legal team assists clients seeking consultation and representation from Delhi for appropriate Supreme Court proceedings, including appeals, Special Leave Petitions, review petitions, transfer petitions and constitutional matters.',
    servicesTitle: 'Supreme Court legal services',
    services: [
      ['Special Leave Petitions', 'Assessment of orders and preparation for an appropriate SLP strategy.'],
      ['Civil appeals', 'Research-led assistance with civil appeals and connected applications.'],
      ['Criminal appeals', 'Representation and advice concerning criminal appellate proceedings.'],
      ['Constitutional matters', 'Structured analysis of questions involving constitutional interpretation.'],
      ['Review petitions', 'Advice on the limited grounds and procedural requirements for review.'],
      ['Transfer petitions', 'Assistance with transfer-related proceedings where legally appropriate.'],
    ],
    courtTitle: 'Supreme Court proceedings from Delhi',
    courtText: 'A Supreme Court matter may involve an appeal, an application for special leave, a review or another proceeding with its own threshold and procedural requirements. The strength of the case depends on the record, the legal question and the relief available—not on broad claims of certainty. A consultation helps establish whether the proposed proceeding is appropriate.',
    clients: ['Individuals', 'Families', 'Companies', 'Professionals', 'Appellants and respondents', 'Parties with constitutional or appellate issues'],
    faqs: [
      ['When should I consult a Supreme Court lawyer in Delhi?', 'Consultation is useful as soon as an appealable order or significant legal issue arises, particularly where limitation, the record or an interim remedy may affect the next step.'],
      ['What is a Special Leave Petition?', 'An SLP is a discretionary route seeking the Supreme Court’s permission to appeal in appropriate cases. Whether it is suitable depends on the order, record and legal grounds.'],
      ['Can a Supreme Court lawyer review my High Court order?', 'Yes. A lawyer can examine the order and underlying record to discuss possible appellate remedies, limitation and the practical prospects of further proceedings.'],
      ['Are Supreme Court outcomes guaranteed?', 'No. Legal representation can improve preparation and clarity, but outcomes depend on the facts, law, record and judicial decision.'],
      ['What should I bring to a Supreme Court consultation?', 'Bring the impugned order, pleadings, evidence, earlier orders, case history and any notices or limitation information available.'],
    ],
  },
  'district-court-lawyer-delhi': {
    slug: 'district-court-lawyer-delhi',
    title: 'District Court Lawyer Delhi',
    metaTitle: 'District Court Lawyer Delhi | Civil, Criminal & Trial Matters | legalgroup',
    metaDescription: 'Consult a district court lawyer in Delhi for civil disputes, criminal matters, bail, property, family, recovery, injunction and trial proceedings.',
    introTitle: 'Ground-level litigation support for Delhi district courts',
    intro: 'District court proceedings often turn on facts, documents, evidence and timely procedural decisions. A clear litigation plan helps clients understand the immediate step as well as the wider course of the matter.',
    introSecond: 'Our court services support individuals, families, property owners, employees and businesses with civil and criminal litigation, bail matters, family disputes, recovery proceedings, injunctions, evidence and trial preparation.',
    servicesTitle: 'District court legal services',
    services: [
      ['Civil disputes', 'Advice and representation for suits, applications and civil procedure.'],
      ['Criminal matters and bail', 'Support through bail hearings, complaints, trials and related proceedings.'],
      ['Property disputes', 'Assistance with possession, title, injunction and property-related claims.'],
      ['Family and matrimonial matters', 'Sensitive representation for appropriate family and matrimonial proceedings.'],
      ['Recovery proceedings', 'Preparation and representation for recovery and contractual claims.'],
      ['Evidence and trial proceedings', 'Systematic preparation of pleadings, evidence, witnesses and arguments.'],
    ],
    courtTitle: 'District court litigation in Delhi',
    courtText: 'Delhi district courts handle a wide range of civil, criminal, family, property and commercial proceedings. The appropriate strategy depends on the court, the nature of the claim, the available evidence and the stage of the case. Timely review can help preserve documents, respond to notices and prepare for the next hearing.',
    clients: ['Individuals', 'Families', 'Property owners', 'Employees and professionals', 'Business owners', 'Parties to civil or criminal disputes'],
    faqs: [
      ['What does a district court lawyer in Delhi handle?', 'Depending on the lawyer’s practice, matters may include civil suits, criminal proceedings, bail, property and family disputes, recovery claims, injunctions and trial work.'],
      ['Can I get advice before responding to a court notice?', 'Yes. A prompt review of the notice, underlying documents and limitation or hearing date can help determine an appropriate response.'],
      ['Do district court matters always go to trial?', 'Not necessarily. Some matters resolve through settlement, mediation, withdrawal, consent orders or other procedural outcomes, while others require evidence and trial.'],
      ['How should I prepare for my first consultation?', 'Bring the notice or pleadings, orders, contracts, correspondence, identity details relevant to the matter and a short chronology of events.'],
      ['Can a lawyer guarantee the result of a district court case?', 'No. A lawyer can provide advice, preparation and representation, but the result depends on the evidence, law and judicial process.'],
    ],
  },
  'litigation-lawyer-delhi': {
    slug: 'litigation-lawyer-delhi',
    title: 'Litigation Lawyer Delhi',
    metaTitle: 'Litigation Lawyer Delhi | Civil, Criminal & Commercial Disputes | legalgroup',
    metaDescription: 'Consult a litigation lawyer in Delhi for civil, criminal, commercial, property, contract, family disputes, appeals and interim relief.',
    introTitle: 'A considered litigation strategy for disputes in Delhi',
    intro: 'Effective litigation begins with understanding the dispute, the evidence and the client’s real objective. The right strategy may involve court representation, an interim application, negotiation, mediation or an appeal.',
    introSecond: 'Our litigation services cover civil and criminal disputes, commercial and contract matters, property and family proceedings, recovery claims, appeals and interim relief. Advice is tailored to the forum, stage and practical context of each matter.',
    servicesTitle: 'Litigation services in Delhi',
    services: [
      ['Civil litigation', 'Representation in disputes involving rights, obligations, possession and relief.'],
      ['Criminal litigation', 'Advice and representation through appropriate criminal proceedings.'],
      ['Commercial and contract disputes', 'Focused preparation for business, contract and recovery disputes.'],
      ['Property and family disputes', 'Strategic support for sensitive property and family litigation.'],
      ['Appeals and interim relief', 'Assessment of urgent remedies, appeals and applications.'],
      ['Settlement and mediation', 'Advice on negotiated resolution where it serves the client’s interests.'],
    ],
    courtTitle: 'Litigation support across Delhi forums',
    courtText: 'A litigation lawyer may help at different stages: before a dispute is filed, after a notice is received, during pleadings and evidence, at interim hearings, on appeal or while exploring settlement. The objective is not to prolong a dispute, but to make informed decisions about the appropriate legal and commercial response.',
    clients: ['Individuals', 'Families', 'Business owners', 'Companies', 'Property owners', 'Parties seeking settlement or representation'],
    faqs: [
      ['What does a litigation lawyer in Delhi do?', 'A litigation lawyer advises on disputes, prepares pleadings and evidence, represents clients at hearings and explains options such as interim relief, appeal, settlement or mediation.'],
      ['Should I try settlement before filing a case?', 'That depends on the facts, urgency, relationship and available remedies. A lawyer can help compare settlement with litigation without compromising a client’s legal position.'],
      ['Can litigation advice be useful before a dispute starts?', 'Yes. Reviewing a contract, notice, proposed claim or evidence early can help reduce avoidable procedural and strategic risks.'],
      ['Does litigation include appeals?', 'Appeals are an important part of litigation strategy, but the route and grounds depend on the order, forum, limitation and applicable law.'],
      ['How long will my litigation matter take?', 'There is no universal timeline. Duration depends on the forum, complexity, evidence, interim applications, hearing schedule and whether the matter resolves earlier.'],
    ],
  },
};

export const COURT_SERVICE_SLUGS = Object.keys(COURT_SERVICE_PAGES);
